typography_spectrum: 0.941391769098118
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.44048950145952404
  lightness: 0.031605725875124335
  saturation: 0.8863572052214295
  rhythmicContrast: 0.9449668598826975
opengraph:
  image: null
  type: null
  appId: 'https://www.facebook.com/BestHealthOption'
layout_spectrum: 0.5849067892413586
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: Best Health Option
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Best Health Option Acupuncture & Wellness
purpose: []
