name: Best Health Option
favicon: null
layout_spectrum: 0.5849067892413586
typography_spectrum: 0.941391769098118
title: 'Best Health Option Acupuncture & Wellness'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.44048950145952404
  lightness: 0.031605725875124335
  saturation: 0.8863572052214295
  rhythmicContrast: 0.9449668598826975
purpose: []
